# Generated by Django 3.0 on 2020-01-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourlunch',
            name='address',
            field=models.CharField(default='', max_length=127, verbose_name='住所'),
        ),
    ]
